custom caching caling service  constructor overwrite
conplementAG/Calinga.NET pull request #28
Opened 2021-02-19 09:52 UTC by ChristianGottinger

add constructor for caching overwrite and some comments for custom caching usage

2021-02-19 14:19 UTC, makmu requested changes

2021-02-19 14:19 UTC, makmu commented on Calinga.NET/Calinga.NET.csproj
> +    <Version>1.6.1</Version>
Please update to 1.7.0 instead: Although the code has hardly been changed I want to make it clear, that we now support a new feature (custom cache services). That's why I think a minor version update is justified

2021-02-22 12:45 UTC, felixse approved these changes

2021-02-22 12:52 UTC, makmu approved these changes

2021-02-22 12:54 UTC, makmu approved these changes

2021-02-22 12:55 UTC, svVys approved these changes

2021-02-23 07:25 UTC, felixse commented on Calinga.NET/CalingaService.cs
> +            await _cachingService.ClearCache();
await -> return

2021-02-23 10:29 UTC, felixse approved these changes

2021-02-23 10:29 UTC, merged